linters-settings:
  goimports:
    local-prefixes: "github.com/namecoin"
  gomoddirectives:
    replace-local: true
    replace-allow-list:
      - "github.com/btcsuite/btcd"
      - "github.com/coreos/go-systemd"
      - "github.com/namecoin/certinject"
      - "github.com/namecoin/x509-compressed"
  varnamelen:
    ignore-type-assert-ok: true
